# PostgreSQL. Versions 9.3 and up are supported.
#   gem install pg
#
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: resept_dev

test:
  <<: *default
  database: resept_test

production:
  <<: *default
  database: resept
